/*
 * NGSI-LD OAS
 * OpenAPI Specification for NGSI-LD API.
 *
 * The version of the OpenAPI document: 1.7.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.LdContext;
import org.openapitools.client.model.LdContextMetadataInner;
import org.openapitools.client.model.RetrieveContext200ResponseOneOf;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RetrieveContext200Response
 */
public class RetrieveContext200ResponseTest {
    private final RetrieveContext200Response model = new RetrieveContext200Response();

    /**
     * Model tests for RetrieveContext200Response
     */
    @Test
    public void testRetrieveContext200Response() {
        // TODO: test RetrieveContext200Response
    }

    /**
     * Test the property 'atContext'
     */
    @Test
    public void atContextTest() {
        // TODO: test atContext
    }

}
