/*
 * NGSI-LD OAS
 * OpenAPI Specification for NGSI-LD API.
 *
 * The version of the OpenAPI document: 1.7.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.net.URI;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.openapitools.client.model.BrandName;
import org.openapitools.client.model.Category;
import org.openapitools.client.model.EntityScope;
import org.openapitools.client.model.GeoProperty;
import org.openapitools.client.model.IsParked;
import org.openapitools.client.model.Passengers;
import org.openapitools.client.model.Route;
import org.openapitools.client.model.Street;
import org.openapitools.client.model.TyreTreadDepths;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * NGSI-LD Entity Type that represents a vehicle. 
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-25T11:21:26.751408096Z[Etc/UTC]", comments = "Generator version: 7.13.0-SNAPSHOT")
public class Vehicle {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private URI id;

  /**
   * NGSI-LD Entity identifier. It has to be Vehicle.
   */
  @JsonAdapter(TypeEnum.Adapter.class)
  public enum TypeEnum {
    VEHICLE("Vehicle");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<TypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return TypeEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      TypeEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  @javax.annotation.Nonnull
  private TypeEnum type = TypeEnum.VEHICLE;

  public static final String SERIALIZED_NAME_SCOPE = "scope";
  @SerializedName(SERIALIZED_NAME_SCOPE)
  @javax.annotation.Nullable
  private EntityScope scope;

  public static final String SERIALIZED_NAME_LOCATION = "location";
  @SerializedName(SERIALIZED_NAME_LOCATION)
  @javax.annotation.Nullable
  private GeoProperty location;

  public static final String SERIALIZED_NAME_OBSERVATION_SPACE = "observationSpace";
  @SerializedName(SERIALIZED_NAME_OBSERVATION_SPACE)
  @javax.annotation.Nullable
  private GeoProperty observationSpace;

  public static final String SERIALIZED_NAME_OPERATION_SPACE = "operationSpace";
  @SerializedName(SERIALIZED_NAME_OPERATION_SPACE)
  @javax.annotation.Nullable
  private GeoProperty operationSpace;

  public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  @javax.annotation.Nullable
  private OffsetDateTime createdAt;

  public static final String SERIALIZED_NAME_MODIFIED_AT = "modifiedAt";
  @SerializedName(SERIALIZED_NAME_MODIFIED_AT)
  @javax.annotation.Nullable
  private OffsetDateTime modifiedAt;

  public static final String SERIALIZED_NAME_DELETED_AT = "deletedAt";
  @SerializedName(SERIALIZED_NAME_DELETED_AT)
  @javax.annotation.Nullable
  private OffsetDateTime deletedAt;

  public static final String SERIALIZED_NAME_BRAND_NAME = "brandName";
  @SerializedName(SERIALIZED_NAME_BRAND_NAME)
  @javax.annotation.Nonnull
  private BrandName brandName;

  public static final String SERIALIZED_NAME_STREET = "street";
  @SerializedName(SERIALIZED_NAME_STREET)
  @javax.annotation.Nullable
  private Street street;

  public static final String SERIALIZED_NAME_IS_PARKED = "isParked";
  @SerializedName(SERIALIZED_NAME_IS_PARKED)
  @javax.annotation.Nonnull
  private IsParked isParked;

  public static final String SERIALIZED_NAME_CATEGORY = "category";
  @SerializedName(SERIALIZED_NAME_CATEGORY)
  @javax.annotation.Nullable
  private Category category;

  public static final String SERIALIZED_NAME_TYRE_TREAD_DEPTHS = "tyreTreadDepths";
  @SerializedName(SERIALIZED_NAME_TYRE_TREAD_DEPTHS)
  @javax.annotation.Nullable
  private TyreTreadDepths tyreTreadDepths;

  public static final String SERIALIZED_NAME_PASSENGERS = "passengers";
  @SerializedName(SERIALIZED_NAME_PASSENGERS)
  @javax.annotation.Nullable
  private Passengers passengers;

  public static final String SERIALIZED_NAME_ROUTE = "route";
  @SerializedName(SERIALIZED_NAME_ROUTE)
  @javax.annotation.Nullable
  private Route route;

  public Vehicle() {
  }

  public Vehicle id(@javax.annotation.Nullable URI id) {
    this.id = id;
    return this;
  }

  /**
   * Entity id. 
   * @return id
   */
  @javax.annotation.Nullable
  public URI getId() {
    return id;
  }

  public void setId(@javax.annotation.Nullable URI id) {
    this.id = id;
  }


  public Vehicle type(@javax.annotation.Nonnull TypeEnum type) {
    this.type = type;
    return this;
  }

  /**
   * NGSI-LD Entity identifier. It has to be Vehicle.
   * @return type
   */
  @javax.annotation.Nonnull
  public TypeEnum getType() {
    return type;
  }

  public void setType(@javax.annotation.Nonnull TypeEnum type) {
    this.type = type;
  }


  public Vehicle scope(@javax.annotation.Nullable EntityScope scope) {
    this.scope = scope;
    return this;
  }

  /**
   * Get scope
   * @return scope
   */
  @javax.annotation.Nullable
  public EntityScope getScope() {
    return scope;
  }

  public void setScope(@javax.annotation.Nullable EntityScope scope) {
    this.scope = scope;
  }


  public Vehicle location(@javax.annotation.Nullable GeoProperty location) {
    this.location = location;
    return this;
  }

  /**
   * Get location
   * @return location
   */
  @javax.annotation.Nullable
  public GeoProperty getLocation() {
    return location;
  }

  public void setLocation(@javax.annotation.Nullable GeoProperty location) {
    this.location = location;
  }


  public Vehicle observationSpace(@javax.annotation.Nullable GeoProperty observationSpace) {
    this.observationSpace = observationSpace;
    return this;
  }

  /**
   * Get observationSpace
   * @return observationSpace
   */
  @javax.annotation.Nullable
  public GeoProperty getObservationSpace() {
    return observationSpace;
  }

  public void setObservationSpace(@javax.annotation.Nullable GeoProperty observationSpace) {
    this.observationSpace = observationSpace;
  }


  public Vehicle operationSpace(@javax.annotation.Nullable GeoProperty operationSpace) {
    this.operationSpace = operationSpace;
    return this;
  }

  /**
   * Get operationSpace
   * @return operationSpace
   */
  @javax.annotation.Nullable
  public GeoProperty getOperationSpace() {
    return operationSpace;
  }

  public void setOperationSpace(@javax.annotation.Nullable GeoProperty operationSpace) {
    this.operationSpace = operationSpace;
  }


  public Vehicle createdAt(@javax.annotation.Nullable OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * It is defined as the temporal Property at which the Entity, Property or Relationship was entered into an NGSI-LD system.  Entity creation timestamp. See clause 4.8. 
   * @return createdAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(@javax.annotation.Nullable OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public Vehicle modifiedAt(@javax.annotation.Nullable OffsetDateTime modifiedAt) {
    this.modifiedAt = modifiedAt;
    return this;
  }

  /**
   * It is defined as the temporal Property at which the Entity, Property or Relationship was last modified in an NGSI-LD system, e.g. in order to correct a previously entered incorrect value.  Entity last modification timestamp. See clause 4.8. 
   * @return modifiedAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getModifiedAt() {
    return modifiedAt;
  }

  public void setModifiedAt(@javax.annotation.Nullable OffsetDateTime modifiedAt) {
    this.modifiedAt = modifiedAt;
  }


  public Vehicle deletedAt(@javax.annotation.Nullable OffsetDateTime deletedAt) {
    this.deletedAt = deletedAt;
    return this;
  }

  /**
   * It is defined as the temporal Property at which the Entity, Property or Relationship was deleted from an NGSI-LD system.  Entity deletion timestamp. See clause 4.8. It is only used in notifications reporting deletions and in the Temporal Representation of Entities (clause 4.5.6), Properties (clause 4.5.7), Relationships (clause 4.5.8) and LanguageProperties (clause 5.2.32). 
   * @return deletedAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getDeletedAt() {
    return deletedAt;
  }

  public void setDeletedAt(@javax.annotation.Nullable OffsetDateTime deletedAt) {
    this.deletedAt = deletedAt;
  }


  public Vehicle brandName(@javax.annotation.Nonnull BrandName brandName) {
    this.brandName = brandName;
    return this;
  }

  /**
   * Get brandName
   * @return brandName
   */
  @javax.annotation.Nonnull
  public BrandName getBrandName() {
    return brandName;
  }

  public void setBrandName(@javax.annotation.Nonnull BrandName brandName) {
    this.brandName = brandName;
  }


  public Vehicle street(@javax.annotation.Nullable Street street) {
    this.street = street;
    return this;
  }

  /**
   * Get street
   * @return street
   */
  @javax.annotation.Nullable
  public Street getStreet() {
    return street;
  }

  public void setStreet(@javax.annotation.Nullable Street street) {
    this.street = street;
  }


  public Vehicle isParked(@javax.annotation.Nonnull IsParked isParked) {
    this.isParked = isParked;
    return this;
  }

  /**
   * Get isParked
   * @return isParked
   */
  @javax.annotation.Nonnull
  public IsParked getIsParked() {
    return isParked;
  }

  public void setIsParked(@javax.annotation.Nonnull IsParked isParked) {
    this.isParked = isParked;
  }


  public Vehicle category(@javax.annotation.Nullable Category category) {
    this.category = category;
    return this;
  }

  /**
   * Get category
   * @return category
   */
  @javax.annotation.Nullable
  public Category getCategory() {
    return category;
  }

  public void setCategory(@javax.annotation.Nullable Category category) {
    this.category = category;
  }


  public Vehicle tyreTreadDepths(@javax.annotation.Nullable TyreTreadDepths tyreTreadDepths) {
    this.tyreTreadDepths = tyreTreadDepths;
    return this;
  }

  /**
   * Get tyreTreadDepths
   * @return tyreTreadDepths
   */
  @javax.annotation.Nullable
  public TyreTreadDepths getTyreTreadDepths() {
    return tyreTreadDepths;
  }

  public void setTyreTreadDepths(@javax.annotation.Nullable TyreTreadDepths tyreTreadDepths) {
    this.tyreTreadDepths = tyreTreadDepths;
  }


  public Vehicle passengers(@javax.annotation.Nullable Passengers passengers) {
    this.passengers = passengers;
    return this;
  }

  /**
   * Get passengers
   * @return passengers
   */
  @javax.annotation.Nullable
  public Passengers getPassengers() {
    return passengers;
  }

  public void setPassengers(@javax.annotation.Nullable Passengers passengers) {
    this.passengers = passengers;
  }


  public Vehicle route(@javax.annotation.Nullable Route route) {
    this.route = route;
    return this;
  }

  /**
   * Get route
   * @return route
   */
  @javax.annotation.Nullable
  public Route getRoute() {
    return route;
  }

  public void setRoute(@javax.annotation.Nullable Route route) {
    this.route = route;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the Vehicle instance itself
   */
  public Vehicle putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Vehicle vehicle = (Vehicle) o;
    return Objects.equals(this.id, vehicle.id) &&
        Objects.equals(this.type, vehicle.type) &&
        Objects.equals(this.scope, vehicle.scope) &&
        Objects.equals(this.location, vehicle.location) &&
        Objects.equals(this.observationSpace, vehicle.observationSpace) &&
        Objects.equals(this.operationSpace, vehicle.operationSpace) &&
        Objects.equals(this.createdAt, vehicle.createdAt) &&
        Objects.equals(this.modifiedAt, vehicle.modifiedAt) &&
        Objects.equals(this.deletedAt, vehicle.deletedAt) &&
        Objects.equals(this.brandName, vehicle.brandName) &&
        Objects.equals(this.street, vehicle.street) &&
        Objects.equals(this.isParked, vehicle.isParked) &&
        Objects.equals(this.category, vehicle.category) &&
        Objects.equals(this.tyreTreadDepths, vehicle.tyreTreadDepths) &&
        Objects.equals(this.passengers, vehicle.passengers) &&
        Objects.equals(this.route, vehicle.route)&&
        Objects.equals(this.additionalProperties, vehicle.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, type, scope, location, observationSpace, operationSpace, createdAt, modifiedAt, deletedAt, brandName, street, isParked, category, tyreTreadDepths, passengers, route, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Vehicle {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    scope: ").append(toIndentedString(scope)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    observationSpace: ").append(toIndentedString(observationSpace)).append("\n");
    sb.append("    operationSpace: ").append(toIndentedString(operationSpace)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    modifiedAt: ").append(toIndentedString(modifiedAt)).append("\n");
    sb.append("    deletedAt: ").append(toIndentedString(deletedAt)).append("\n");
    sb.append("    brandName: ").append(toIndentedString(brandName)).append("\n");
    sb.append("    street: ").append(toIndentedString(street)).append("\n");
    sb.append("    isParked: ").append(toIndentedString(isParked)).append("\n");
    sb.append("    category: ").append(toIndentedString(category)).append("\n");
    sb.append("    tyreTreadDepths: ").append(toIndentedString(tyreTreadDepths)).append("\n");
    sb.append("    passengers: ").append(toIndentedString(passengers)).append("\n");
    sb.append("    route: ").append(toIndentedString(route)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("type");
    openapiFields.add("scope");
    openapiFields.add("location");
    openapiFields.add("observationSpace");
    openapiFields.add("operationSpace");
    openapiFields.add("createdAt");
    openapiFields.add("modifiedAt");
    openapiFields.add("deletedAt");
    openapiFields.add("brandName");
    openapiFields.add("street");
    openapiFields.add("isParked");
    openapiFields.add("category");
    openapiFields.add("tyreTreadDepths");
    openapiFields.add("passengers");
    openapiFields.add("route");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("type");
    openapiRequiredFields.add("brandName");
    openapiRequiredFields.add("isParked");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Vehicle
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Vehicle.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in Vehicle is not found in the empty JSON string", Vehicle.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : Vehicle.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if (!jsonObj.get("type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("type").toString()));
      }
      // validate the required field `type`
      TypeEnum.validateJsonElement(jsonObj.get("type"));
      // validate the optional field `scope`
      if (jsonObj.get("scope") != null && !jsonObj.get("scope").isJsonNull()) {
        EntityScope.validateJsonElement(jsonObj.get("scope"));
      }
      // validate the required field `brandName`
      BrandName.validateJsonElement(jsonObj.get("brandName"));
      // validate the optional field `street`
      if (jsonObj.get("street") != null && !jsonObj.get("street").isJsonNull()) {
        Street.validateJsonElement(jsonObj.get("street"));
      }
      // validate the required field `isParked`
      IsParked.validateJsonElement(jsonObj.get("isParked"));
      // validate the optional field `category`
      if (jsonObj.get("category") != null && !jsonObj.get("category").isJsonNull()) {
        Category.validateJsonElement(jsonObj.get("category"));
      }
      // validate the optional field `tyreTreadDepths`
      if (jsonObj.get("tyreTreadDepths") != null && !jsonObj.get("tyreTreadDepths").isJsonNull()) {
        TyreTreadDepths.validateJsonElement(jsonObj.get("tyreTreadDepths"));
      }
      // validate the optional field `passengers`
      if (jsonObj.get("passengers") != null && !jsonObj.get("passengers").isJsonNull()) {
        Passengers.validateJsonElement(jsonObj.get("passengers"));
      }
      // validate the optional field `route`
      if (jsonObj.get("route") != null && !jsonObj.get("route").isJsonNull()) {
        Route.validateJsonElement(jsonObj.get("route"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Vehicle.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Vehicle' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Vehicle> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Vehicle.class));

       return (TypeAdapter<T>) new TypeAdapter<Vehicle>() {
           @Override
           public void write(JsonWriter out, Vehicle value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public Vehicle read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             Vehicle instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Vehicle given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Vehicle
   * @throws IOException if the JSON string is invalid with respect to Vehicle
   */
  public static Vehicle fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Vehicle.class);
  }

  /**
   * Convert an instance of Vehicle to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

