/*
 * NGSI-LD OAS
 * OpenAPI Specification for NGSI-LD API.
 *
 * The version of the OpenAPI document: 1.7.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.openapitools.client.model.ProvidedBy;
import org.openapitools.client.model.Reliability;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * NGSI-LD Property Type. The available spot number. 
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-25T10:47:39.074561198Z[Etc/UTC]", comments = "Generator version: 7.13.0-SNAPSHOT")
public class AvailableSpotNumber {
  public static final String SERIALIZED_NAME_VALUE = "value";
  @SerializedName(SERIALIZED_NAME_VALUE)
  @javax.annotation.Nonnull
  private BigDecimal value;

  public static final String SERIALIZED_NAME_RELIABILITY = "reliability";
  @SerializedName(SERIALIZED_NAME_RELIABILITY)
  @javax.annotation.Nullable
  private Reliability reliability;

  public static final String SERIALIZED_NAME_PROVIDED_BY = "providedBy";
  @SerializedName(SERIALIZED_NAME_PROVIDED_BY)
  @javax.annotation.Nullable
  private ProvidedBy providedBy;

  public AvailableSpotNumber() {
  }

  public AvailableSpotNumber value(@javax.annotation.Nonnull BigDecimal value) {
    this.value = value;
    return this;
  }

  /**
   * Get value
   * @return value
   */
  @javax.annotation.Nonnull
  public BigDecimal getValue() {
    return value;
  }

  public void setValue(@javax.annotation.Nonnull BigDecimal value) {
    this.value = value;
  }


  public AvailableSpotNumber reliability(@javax.annotation.Nullable Reliability reliability) {
    this.reliability = reliability;
    return this;
  }

  /**
   * Get reliability
   * @return reliability
   */
  @javax.annotation.Nullable
  public Reliability getReliability() {
    return reliability;
  }

  public void setReliability(@javax.annotation.Nullable Reliability reliability) {
    this.reliability = reliability;
  }


  public AvailableSpotNumber providedBy(@javax.annotation.Nullable ProvidedBy providedBy) {
    this.providedBy = providedBy;
    return this;
  }

  /**
   * Get providedBy
   * @return providedBy
   */
  @javax.annotation.Nullable
  public ProvidedBy getProvidedBy() {
    return providedBy;
  }

  public void setProvidedBy(@javax.annotation.Nullable ProvidedBy providedBy) {
    this.providedBy = providedBy;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AvailableSpotNumber availableSpotNumber = (AvailableSpotNumber) o;
    return Objects.equals(this.value, availableSpotNumber.value) &&
        Objects.equals(this.reliability, availableSpotNumber.reliability) &&
        Objects.equals(this.providedBy, availableSpotNumber.providedBy);
  }

  @Override
  public int hashCode() {
    return Objects.hash(value, reliability, providedBy);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AvailableSpotNumber {\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    reliability: ").append(toIndentedString(reliability)).append("\n");
    sb.append("    providedBy: ").append(toIndentedString(providedBy)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("value");
    openapiFields.add("reliability");
    openapiFields.add("providedBy");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("value");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to AvailableSpotNumber
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!AvailableSpotNumber.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in AvailableSpotNumber is not found in the empty JSON string", AvailableSpotNumber.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!AvailableSpotNumber.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `AvailableSpotNumber` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : AvailableSpotNumber.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `reliability`
      if (jsonObj.get("reliability") != null && !jsonObj.get("reliability").isJsonNull()) {
        Reliability.validateJsonElement(jsonObj.get("reliability"));
      }
      // validate the optional field `providedBy`
      if (jsonObj.get("providedBy") != null && !jsonObj.get("providedBy").isJsonNull()) {
        ProvidedBy.validateJsonElement(jsonObj.get("providedBy"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AvailableSpotNumber.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AvailableSpotNumber' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AvailableSpotNumber> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AvailableSpotNumber.class));

       return (TypeAdapter<T>) new TypeAdapter<AvailableSpotNumber>() {
           @Override
           public void write(JsonWriter out, AvailableSpotNumber value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public AvailableSpotNumber read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of AvailableSpotNumber given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of AvailableSpotNumber
   * @throws IOException if the JSON string is invalid with respect to AvailableSpotNumber
   */
  public static AvailableSpotNumber fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AvailableSpotNumber.class);
  }

  /**
   * Convert an instance of AvailableSpotNumber to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

