/*
 * NGSI-LD OAS
 * OpenAPI Specification for NGSI-LD API.
 *
 * The version of the OpenAPI document: 1.7.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.List;
import org.openapitools.client.model.GeoProperty;
import org.openapitools.client.model.LanguageProperty;
import org.openapitools.client.model.Property;
import org.openapitools.client.model.Relationship;
import org.openapitools.client.model.VocabularyProperty;



import java.io.IOException;
import java.lang.reflect.Type;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.JsonPrimitive;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonSerializationContext;
import com.google.gson.JsonSerializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonArray;
import com.google.gson.JsonParseException;

import org.openapitools.client.JSON;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-25T10:47:39.074561198Z[Etc/UTC]", comments = "Generator version: 7.13.0-SNAPSHOT")
public class EntityTemporalValue extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(EntityTemporalValue.class.getName());

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!EntityTemporalValue.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'EntityTemporalValue' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);

            final Type typeInstanceListProperty = new TypeToken<List<Property>>(){}.getType();
            final TypeAdapter<List<Property>> adapterListProperty = (TypeAdapter<List<Property>>) gson.getDelegateAdapter(this, TypeToken.get(typeInstanceListProperty));

            final Type typeInstanceListRelationship = new TypeToken<List<Relationship>>(){}.getType();
            final TypeAdapter<List<Relationship>> adapterListRelationship = (TypeAdapter<List<Relationship>>) gson.getDelegateAdapter(this, TypeToken.get(typeInstanceListRelationship));

            final Type typeInstanceListGeoProperty = new TypeToken<List<GeoProperty>>(){}.getType();
            final TypeAdapter<List<GeoProperty>> adapterListGeoProperty = (TypeAdapter<List<GeoProperty>>) gson.getDelegateAdapter(this, TypeToken.get(typeInstanceListGeoProperty));

            final Type typeInstanceListLanguageProperty = new TypeToken<List<LanguageProperty>>(){}.getType();
            final TypeAdapter<List<LanguageProperty>> adapterListLanguageProperty = (TypeAdapter<List<LanguageProperty>>) gson.getDelegateAdapter(this, TypeToken.get(typeInstanceListLanguageProperty));

            final Type typeInstanceListVocabularyProperty = new TypeToken<List<VocabularyProperty>>(){}.getType();
            final TypeAdapter<List<VocabularyProperty>> adapterListVocabularyProperty = (TypeAdapter<List<VocabularyProperty>>) gson.getDelegateAdapter(this, TypeToken.get(typeInstanceListVocabularyProperty));

            return (TypeAdapter<T>) new TypeAdapter<EntityTemporalValue>() {
                @Override
                public void write(JsonWriter out, EntityTemporalValue value) throws IOException {
                    if (value == null || value.getActualInstance() == null) {
                        elementAdapter.write(out, null);
                        return;
                    }

                    // check if the actual instance is of the type `List<Property>`
                    if (value.getActualInstance() instanceof List<?>) {
                        List<?> list = (List<?>) value.getActualInstance();
                        if (list.get(0) instanceof Property) {
                            JsonArray array = adapterListProperty.toJsonTree((List<Property>)value.getActualInstance()).getAsJsonArray();
                            elementAdapter.write(out, array);
                            return;
                        }
                    }
                    throw new IOException("Failed to serialize as the type doesn't match oneOf schemas: List<GeoProperty>, List<LanguageProperty>, List<Property>, List<Relationship>, List<VocabularyProperty>");
                }

                @Override
                public EntityTemporalValue read(JsonReader in) throws IOException {
                    Object deserialized = null;
                    JsonElement jsonElement = elementAdapter.read(in);

                    int match = 0;
                    ArrayList<String> errorMessages = new ArrayList<>();
                    TypeAdapter actualAdapter = elementAdapter;

                    // deserialize List<Property>
                    try {
                        // validate the JSON object to see if any exception is thrown
                        if (!jsonElement.isJsonArray()) {
                            throw new IllegalArgumentException(String.format("Expected json element to be a array type in the JSON string but got `%s`", jsonElement.toString()));
                        }

                        JsonArray array = jsonElement.getAsJsonArray();
                        // validate array items
                        for(JsonElement element : array) {
                            Property.validateJsonElement(element);
                        }
                        actualAdapter = adapterListProperty;
                        match++;
                        log.log(Level.FINER, "Input data matches schema 'List<Property>'");
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format("Deserialization for List<Property> failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'List<Property>'", e);
                    }

                    if (match == 1) {
                        EntityTemporalValue ret = new EntityTemporalValue();
                        ret.setActualInstance(actualAdapter.fromJsonTree(jsonElement));
                        return ret;
                    }

                    throw new IOException(String.format("Failed deserialization for EntityTemporalValue: %d classes match result, expected 1. Detailed failure message for oneOf schemas: %s. JSON: %s", match, errorMessages, jsonElement.toString()));
                }
            }.nullSafe();
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, Class<?>> schemas = new HashMap<String, Class<?>>();

    public EntityTemporalValue() {
        super("oneOf", Boolean.FALSE);
    }

    public EntityTemporalValue(Object o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("List<Property>", List.class);
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return EntityTemporalValue.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * List<GeoProperty>, List<LanguageProperty>, List<Property>, List<Relationship>, List<VocabularyProperty>
     *
     * It could be an instance of the 'oneOf' schemas.
     */
    @Override
    public void setActualInstance(Object instance) {
        if (instance instanceof List<?>) {
            List<?> list = (List<?>) instance;
            if (list.get(0) instanceof Property) {
                super.setActualInstance(instance);
                return;
            }
        }

        throw new RuntimeException("Invalid instance type. Must be List<GeoProperty>, List<LanguageProperty>, List<Property>, List<Relationship>, List<VocabularyProperty>");
    }

    /**
     * Get the actual instance, which can be the following:
     * List<GeoProperty>, List<LanguageProperty>, List<Property>, List<Relationship>, List<VocabularyProperty>
     *
     * @return The actual instance (List<GeoProperty>, List<LanguageProperty>, List<Property>, List<Relationship>, List<VocabularyProperty>)
     */
    @SuppressWarnings("unchecked")
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `List<Property>`. If the actual instance is not `List<Property>`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `List<Property>`
     * @throws ClassCastException if the instance is not `List<Property>`
     */
    public List<Property> getListProperty() throws ClassCastException {
        return (List<Property>)super.getActualInstance();
    }

    /**
     * Get the actual instance of `List<Relationship>`. If the actual instance is not `List<Relationship>`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `List<Relationship>`
     * @throws ClassCastException if the instance is not `List<Relationship>`
     */
    public List<Relationship> getListRelationship() throws ClassCastException {
        return (List<Relationship>)super.getActualInstance();
    }

    /**
     * Get the actual instance of `List<GeoProperty>`. If the actual instance is not `List<GeoProperty>`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `List<GeoProperty>`
     * @throws ClassCastException if the instance is not `List<GeoProperty>`
     */
    public List<GeoProperty> getListGeoProperty() throws ClassCastException {
        return (List<GeoProperty>)super.getActualInstance();
    }

    /**
     * Get the actual instance of `List<LanguageProperty>`. If the actual instance is not `List<LanguageProperty>`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `List<LanguageProperty>`
     * @throws ClassCastException if the instance is not `List<LanguageProperty>`
     */
    public List<LanguageProperty> getListLanguageProperty() throws ClassCastException {
        return (List<LanguageProperty>)super.getActualInstance();
    }

    /**
     * Get the actual instance of `List<VocabularyProperty>`. If the actual instance is not `List<VocabularyProperty>`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `List<VocabularyProperty>`
     * @throws ClassCastException if the instance is not `List<VocabularyProperty>`
     */
    public List<VocabularyProperty> getListVocabularyProperty() throws ClassCastException {
        return (List<VocabularyProperty>)super.getActualInstance();
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to EntityTemporalValue
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        // validate oneOf schemas one by one
        int validCount = 0;
        ArrayList<String> errorMessages = new ArrayList<>();
        // validate the json string with List<Property>
        try {
            if (!jsonElement.isJsonArray()) {
                throw new IllegalArgumentException(String.format("Expected json element to be a array type in the JSON string but got `%s`", jsonElement.toString()));
            }
            JsonArray array = jsonElement.getAsJsonArray();
            // validate array items
            for(JsonElement element : array) {
                Property.validateJsonElement(element);
            }
            validCount++;
        } catch (Exception e) {
            errorMessages.add(String.format("Deserialization for List<Property> failed with `%s`.", e.getMessage()));
            // continue to the next one
        }
        if (validCount != 1) {
            throw new IOException(String.format("The JSON string is invalid for EntityTemporalValue with oneOf schemas: List<GeoProperty>, List<LanguageProperty>, List<Property>, List<Relationship>, List<VocabularyProperty>. %d class(es) match the result, expected 1. Detailed failure message for oneOf schemas: %s. JSON: %s", validCount, errorMessages, jsonElement.toString()));
        }
    }

    /**
     * Create an instance of EntityTemporalValue given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of EntityTemporalValue
     * @throws IOException if the JSON string is invalid with respect to EntityTemporalValue
     */
    public static EntityTemporalValue fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, EntityTemporalValue.class);
    }

    /**
     * Convert an instance of EntityTemporalValue to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}

