/*
 * NGSI-LD OAS
 * OpenAPI Specification for NGSI-LD API.
 *
 * The version of the OpenAPI document: 1.7.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.net.URI;
import java.util.List;
import org.openapitools.client.model.LdContextMetadataInner;



import java.io.IOException;
import java.lang.reflect.Type;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.JsonPrimitive;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonSerializationContext;
import com.google.gson.JsonSerializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonArray;
import com.google.gson.JsonParseException;

import org.openapitools.client.JSON;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-25T10:47:39.074561198Z[Etc/UTC]", comments = "Generator version: 7.13.0-SNAPSHOT")
public class ListContexts200Response extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(ListContexts200Response.class.getName());

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!ListContexts200Response.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'ListContexts200Response' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);

            final Type typeInstanceListURI = new TypeToken<List<URI>>(){}.getType();
            final TypeAdapter<List<URI>> adapterListURI = (TypeAdapter<List<URI>>) gson.getDelegateAdapter(this, TypeToken.get(typeInstanceListURI));

            final Type typeInstanceListListLdContextMetadataInner = new TypeToken<List<List<LdContextMetadataInner>>>(){}.getType();
            final TypeAdapter<List<List<LdContextMetadataInner>>> adapterListListLdContextMetadataInner = (TypeAdapter<List<List<LdContextMetadataInner>>>) gson.getDelegateAdapter(this, TypeToken.get(typeInstanceListListLdContextMetadataInner));

            return (TypeAdapter<T>) new TypeAdapter<ListContexts200Response>() {
                @Override
                public void write(JsonWriter out, ListContexts200Response value) throws IOException {
                    if (value == null || value.getActualInstance() == null) {
                        elementAdapter.write(out, null);
                        return;
                    }

                    // check if the actual instance is of the type `List<URI>`
                    if (value.getActualInstance() instanceof List<?>) {
                        List<?> list = (List<?>) value.getActualInstance();
                        if (list.get(0) instanceof URI) {
                            JsonArray array = adapterListURI.toJsonTree((List<URI>)value.getActualInstance()).getAsJsonArray();
                            elementAdapter.write(out, array);
                            return;
                        }
                    }
                    throw new IOException("Failed to serialize as the type doesn't match oneOf schemas: List<List<LdContextMetadataInner>>, List<URI>");
                }

                @Override
                public ListContexts200Response read(JsonReader in) throws IOException {
                    Object deserialized = null;
                    JsonElement jsonElement = elementAdapter.read(in);

                    int match = 0;
                    ArrayList<String> errorMessages = new ArrayList<>();
                    TypeAdapter actualAdapter = elementAdapter;

                    // deserialize List<URI>
                    try {
                        // validate the JSON object to see if any exception is thrown
                        if (!jsonElement.isJsonArray()) {
                            throw new IllegalArgumentException(String.format("Expected json element to be a array type in the JSON string but got `%s`", jsonElement.toString()));
                        }

                        JsonArray array = jsonElement.getAsJsonArray();
                        // validate array items
                        for(JsonElement element : array) {
                        }
                        actualAdapter = adapterListURI;
                        match++;
                        log.log(Level.FINER, "Input data matches schema 'List<URI>'");
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format("Deserialization for List<URI> failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'List<URI>'", e);
                    }

                    if (match == 1) {
                        ListContexts200Response ret = new ListContexts200Response();
                        ret.setActualInstance(actualAdapter.fromJsonTree(jsonElement));
                        return ret;
                    }

                    throw new IOException(String.format("Failed deserialization for ListContexts200Response: %d classes match result, expected 1. Detailed failure message for oneOf schemas: %s. JSON: %s", match, errorMessages, jsonElement.toString()));
                }
            }.nullSafe();
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, Class<?>> schemas = new HashMap<String, Class<?>>();

    public ListContexts200Response() {
        super("oneOf", Boolean.FALSE);
    }

    public ListContexts200Response(Object o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("List<URI>", List.class);
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return ListContexts200Response.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * List<List<LdContextMetadataInner>>, List<URI>
     *
     * It could be an instance of the 'oneOf' schemas.
     */
    @Override
    public void setActualInstance(Object instance) {
        if (instance instanceof List<?>) {
            List<?> list = (List<?>) instance;
            if (list.get(0) instanceof URI) {
                super.setActualInstance(instance);
                return;
            }
        }

        throw new RuntimeException("Invalid instance type. Must be List<List<LdContextMetadataInner>>, List<URI>");
    }

    /**
     * Get the actual instance, which can be the following:
     * List<List<LdContextMetadataInner>>, List<URI>
     *
     * @return The actual instance (List<List<LdContextMetadataInner>>, List<URI>)
     */
    @SuppressWarnings("unchecked")
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `List<URI>`. If the actual instance is not `List<URI>`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `List<URI>`
     * @throws ClassCastException if the instance is not `List<URI>`
     */
    public List<URI> getListURI() throws ClassCastException {
        return (List<URI>)super.getActualInstance();
    }

    /**
     * Get the actual instance of `List<List<LdContextMetadataInner>>`. If the actual instance is not `List<List<LdContextMetadataInner>>`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `List<List<LdContextMetadataInner>>`
     * @throws ClassCastException if the instance is not `List<List<LdContextMetadataInner>>`
     */
    public List<List<LdContextMetadataInner>> getListListLdContextMetadataInner() throws ClassCastException {
        return (List<List<LdContextMetadataInner>>)super.getActualInstance();
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to ListContexts200Response
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        // validate oneOf schemas one by one
        int validCount = 0;
        ArrayList<String> errorMessages = new ArrayList<>();
        // validate the json string with List<URI>
        try {
            if (!jsonElement.isJsonArray()) {
                throw new IllegalArgumentException(String.format("Expected json element to be a array type in the JSON string but got `%s`", jsonElement.toString()));
            }
            JsonArray array = jsonElement.getAsJsonArray();
            // validate array items
            for(JsonElement element : array) {
            }
            validCount++;
        } catch (Exception e) {
            errorMessages.add(String.format("Deserialization for List<URI> failed with `%s`.", e.getMessage()));
            // continue to the next one
        }
        if (validCount != 1) {
            throw new IOException(String.format("The JSON string is invalid for ListContexts200Response with oneOf schemas: List<List<LdContextMetadataInner>>, List<URI>. %d class(es) match the result, expected 1. Detailed failure message for oneOf schemas: %s. JSON: %s", validCount, errorMessages, jsonElement.toString()));
        }
    }

    /**
     * Create an instance of ListContexts200Response given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of ListContexts200Response
     * @throws IOException if the JSON string is invalid with respect to ListContexts200Response
     */
    public static ListContexts200Response fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, ListContexts200Response.class);
    }

    /**
     * Convert an instance of ListContexts200Response to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}

