/*
 * NGSI-LD OAS
 * OpenAPI Specification for NGSI-LD API.
 *
 * The version of the OpenAPI document: 1.7.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * 6.3.12 Simplified or aggregated temporal representation of entities.  When its value includes the keyword \&quot;temporalValues\&quot;, a simplified temporal representation of entities shall be provided as defined by clause 4.5.8.  When its value includes the keyword \&quot;aggregatedValues\&quot;, an aggregated temporal representation of entities shall be provided as defined by clause 4.5.19.  Only one of the two keywords can be present in the values of the parameter. 
 */
@JsonAdapter(OptionsTemporal.Adapter.class)
public enum OptionsTemporal {
  
  TEMPORAL_VALUES("temporalValues"),
  
  AGGREGATED_VALUES("aggregatedValues");

  private String value;

  OptionsTemporal(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static OptionsTemporal fromValue(String value) {
    for (OptionsTemporal b : OptionsTemporal.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<OptionsTemporal> {
    @Override
    public void write(final JsonWriter jsonWriter, final OptionsTemporal enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public OptionsTemporal read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return OptionsTemporal.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    OptionsTemporal.fromValue(value);
  }
}

