/*
 * NGSI-LD OAS
 * OpenAPI Specification for NGSI-LD API.
 *
 * The version of the OpenAPI document: 1.7.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * 6.16.3 For POST method associated to the operations \&quot;Batch Entity Update\&quot; and \&quot;Append Entity Attributes\&quot;, the \&quot;noOvevwrite\&quot;  options query parameter indicates that no attribute overwrite shall be performed. 
 */
@JsonAdapter(OptionsNoOverwrite.Adapter.class)
public enum OptionsNoOverwrite {
  
  NO_OVERWRITE("noOverwrite");

  private String value;

  OptionsNoOverwrite(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static OptionsNoOverwrite fromValue(String value) {
    for (OptionsNoOverwrite b : OptionsNoOverwrite.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<OptionsNoOverwrite> {
    @Override
    public void write(final JsonWriter jsonWriter, final OptionsNoOverwrite enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public OptionsNoOverwrite read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return OptionsNoOverwrite.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    OptionsNoOverwrite.fromValue(value);
  }
}

