/*
 * NGSI-LD OAS
 * OpenAPI Specification for NGSI-LD API.
 *
 * The version of the OpenAPI document: 1.7.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.net.URI;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.LdContext;
import org.openapitools.client.model.RetrieveAttrTypes200Response1OneOf;
import org.openapitools.client.model.RetrieveAttrTypes200Response1OneOf1Inner;



import java.io.IOException;
import java.lang.reflect.Type;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.JsonPrimitive;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonSerializationContext;
import com.google.gson.JsonSerializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonArray;
import com.google.gson.JsonParseException;

import org.openapitools.client.JSON;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-25T11:21:26.751408096Z[Etc/UTC]", comments = "Generator version: 7.13.0-SNAPSHOT")
public class RetrieveAttrTypes200Response1 extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(RetrieveAttrTypes200Response1.class.getName());

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!RetrieveAttrTypes200Response1.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'RetrieveAttrTypes200Response1' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<RetrieveAttrTypes200Response1OneOf> adapterRetrieveAttrTypes200Response1OneOf = gson.getDelegateAdapter(this, TypeToken.get(RetrieveAttrTypes200Response1OneOf.class));

            final Type typeInstanceListRetrieveAttrTypes200Response1OneOf1Inner = new TypeToken<List<RetrieveAttrTypes200Response1OneOf1Inner>>(){}.getType();
            final TypeAdapter<List<RetrieveAttrTypes200Response1OneOf1Inner>> adapterListRetrieveAttrTypes200Response1OneOf1Inner = (TypeAdapter<List<RetrieveAttrTypes200Response1OneOf1Inner>>) gson.getDelegateAdapter(this, TypeToken.get(typeInstanceListRetrieveAttrTypes200Response1OneOf1Inner));

            return (TypeAdapter<T>) new TypeAdapter<RetrieveAttrTypes200Response1>() {
                @Override
                public void write(JsonWriter out, RetrieveAttrTypes200Response1 value) throws IOException {
                    if (value == null || value.getActualInstance() == null) {
                        elementAdapter.write(out, null);
                        return;
                    }

                    // check if the actual instance is of the type `RetrieveAttrTypes200Response1OneOf`
                    if (value.getActualInstance() instanceof RetrieveAttrTypes200Response1OneOf) {
                        JsonElement element = adapterRetrieveAttrTypes200Response1OneOf.toJsonTree((RetrieveAttrTypes200Response1OneOf)value.getActualInstance());
                        elementAdapter.write(out, element);
                        return;
                    }
                    // check if the actual instance is of the type `List<RetrieveAttrTypes200Response1OneOf1Inner>`
                    if (value.getActualInstance() instanceof List<?>) {
                        List<?> list = (List<?>) value.getActualInstance();
                        if (list.get(0) instanceof RetrieveAttrTypes200Response1OneOf1Inner) {
                            JsonArray array = adapterListRetrieveAttrTypes200Response1OneOf1Inner.toJsonTree((List<RetrieveAttrTypes200Response1OneOf1Inner>)value.getActualInstance()).getAsJsonArray();
                            elementAdapter.write(out, array);
                            return;
                        }
                    }
                    throw new IOException("Failed to serialize as the type doesn't match oneOf schemas: List<RetrieveAttrTypes200Response1OneOf1Inner>, RetrieveAttrTypes200Response1OneOf");
                }

                @Override
                public RetrieveAttrTypes200Response1 read(JsonReader in) throws IOException {
                    Object deserialized = null;
                    JsonElement jsonElement = elementAdapter.read(in);

                    int match = 0;
                    ArrayList<String> errorMessages = new ArrayList<>();
                    TypeAdapter actualAdapter = elementAdapter;

                    // deserialize RetrieveAttrTypes200Response1OneOf
                    try {
                        // validate the JSON object to see if any exception is thrown
                        RetrieveAttrTypes200Response1OneOf.validateJsonElement(jsonElement);
                        actualAdapter = adapterRetrieveAttrTypes200Response1OneOf;
                        match++;
                        log.log(Level.FINER, "Input data matches schema 'RetrieveAttrTypes200Response1OneOf'");
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format("Deserialization for RetrieveAttrTypes200Response1OneOf failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'RetrieveAttrTypes200Response1OneOf'", e);
                    }
                    // deserialize List<RetrieveAttrTypes200Response1OneOf1Inner>
                    try {
                        // validate the JSON object to see if any exception is thrown
                        if (!jsonElement.isJsonArray()) {
                            throw new IllegalArgumentException(String.format("Expected json element to be a array type in the JSON string but got `%s`", jsonElement.toString()));
                        }

                        JsonArray array = jsonElement.getAsJsonArray();
                        // validate array items
                        for(JsonElement element : array) {
                            RetrieveAttrTypes200Response1OneOf1Inner.validateJsonElement(element);
                        }
                        actualAdapter = adapterListRetrieveAttrTypes200Response1OneOf1Inner;
                        match++;
                        log.log(Level.FINER, "Input data matches schema 'List<RetrieveAttrTypes200Response1OneOf1Inner>'");
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format("Deserialization for List<RetrieveAttrTypes200Response1OneOf1Inner> failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'List<RetrieveAttrTypes200Response1OneOf1Inner>'", e);
                    }

                    if (match == 1) {
                        RetrieveAttrTypes200Response1 ret = new RetrieveAttrTypes200Response1();
                        ret.setActualInstance(actualAdapter.fromJsonTree(jsonElement));
                        return ret;
                    }

                    throw new IOException(String.format("Failed deserialization for RetrieveAttrTypes200Response1: %d classes match result, expected 1. Detailed failure message for oneOf schemas: %s. JSON: %s", match, errorMessages, jsonElement.toString()));
                }
            }.nullSafe();
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, Class<?>> schemas = new HashMap<String, Class<?>>();

    public RetrieveAttrTypes200Response1() {
        super("oneOf", Boolean.FALSE);
    }

    public RetrieveAttrTypes200Response1(Object o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("RetrieveAttrTypes200Response1OneOf", RetrieveAttrTypes200Response1OneOf.class);
        schemas.put("List<RetrieveAttrTypes200Response1OneOf1Inner>", List.class);
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return RetrieveAttrTypes200Response1.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * List<RetrieveAttrTypes200Response1OneOf1Inner>, RetrieveAttrTypes200Response1OneOf
     *
     * It could be an instance of the 'oneOf' schemas.
     */
    @Override
    public void setActualInstance(Object instance) {
        if (instance instanceof RetrieveAttrTypes200Response1OneOf) {
            super.setActualInstance(instance);
            return;
        }

        if (instance instanceof List<?>) {
            List<?> list = (List<?>) instance;
            if (list.get(0) instanceof RetrieveAttrTypes200Response1OneOf1Inner) {
                super.setActualInstance(instance);
                return;
            }
        }

        throw new RuntimeException("Invalid instance type. Must be List<RetrieveAttrTypes200Response1OneOf1Inner>, RetrieveAttrTypes200Response1OneOf");
    }

    /**
     * Get the actual instance, which can be the following:
     * List<RetrieveAttrTypes200Response1OneOf1Inner>, RetrieveAttrTypes200Response1OneOf
     *
     * @return The actual instance (List<RetrieveAttrTypes200Response1OneOf1Inner>, RetrieveAttrTypes200Response1OneOf)
     */
    @SuppressWarnings("unchecked")
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `RetrieveAttrTypes200Response1OneOf`. If the actual instance is not `RetrieveAttrTypes200Response1OneOf`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `RetrieveAttrTypes200Response1OneOf`
     * @throws ClassCastException if the instance is not `RetrieveAttrTypes200Response1OneOf`
     */
    public RetrieveAttrTypes200Response1OneOf getRetrieveAttrTypes200Response1OneOf() throws ClassCastException {
        return (RetrieveAttrTypes200Response1OneOf)super.getActualInstance();
    }

    /**
     * Get the actual instance of `List<RetrieveAttrTypes200Response1OneOf1Inner>`. If the actual instance is not `List<RetrieveAttrTypes200Response1OneOf1Inner>`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `List<RetrieveAttrTypes200Response1OneOf1Inner>`
     * @throws ClassCastException if the instance is not `List<RetrieveAttrTypes200Response1OneOf1Inner>`
     */
    public List<RetrieveAttrTypes200Response1OneOf1Inner> getListRetrieveAttrTypes200Response1OneOf1Inner() throws ClassCastException {
        return (List<RetrieveAttrTypes200Response1OneOf1Inner>)super.getActualInstance();
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to RetrieveAttrTypes200Response1
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        // validate oneOf schemas one by one
        int validCount = 0;
        ArrayList<String> errorMessages = new ArrayList<>();
        // validate the json string with RetrieveAttrTypes200Response1OneOf
        try {
            RetrieveAttrTypes200Response1OneOf.validateJsonElement(jsonElement);
            validCount++;
        } catch (Exception e) {
            errorMessages.add(String.format("Deserialization for RetrieveAttrTypes200Response1OneOf failed with `%s`.", e.getMessage()));
            // continue to the next one
        }
        // validate the json string with List<RetrieveAttrTypes200Response1OneOf1Inner>
        try {
            if (!jsonElement.isJsonArray()) {
                throw new IllegalArgumentException(String.format("Expected json element to be a array type in the JSON string but got `%s`", jsonElement.toString()));
            }
            JsonArray array = jsonElement.getAsJsonArray();
            // validate array items
            for(JsonElement element : array) {
                RetrieveAttrTypes200Response1OneOf1Inner.validateJsonElement(element);
            }
            validCount++;
        } catch (Exception e) {
            errorMessages.add(String.format("Deserialization for List<RetrieveAttrTypes200Response1OneOf1Inner> failed with `%s`.", e.getMessage()));
            // continue to the next one
        }
        if (validCount != 1) {
            throw new IOException(String.format("The JSON string is invalid for RetrieveAttrTypes200Response1 with oneOf schemas: List<RetrieveAttrTypes200Response1OneOf1Inner>, RetrieveAttrTypes200Response1OneOf. %d class(es) match the result, expected 1. Detailed failure message for oneOf schemas: %s. JSON: %s", validCount, errorMessages, jsonElement.toString()));
        }
    }

    /**
     * Create an instance of RetrieveAttrTypes200Response1 given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of RetrieveAttrTypes200Response1
     * @throws IOException if the JSON string is invalid with respect to RetrieveAttrTypes200Response1
     */
    public static RetrieveAttrTypes200Response1 fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, RetrieveAttrTypes200Response1.class);
    }

    /**
     * Convert an instance of RetrieveAttrTypes200Response1 to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}

