/*
 * NGSI-LD OAS
 * OpenAPI Specification for NGSI-LD API.
 *
 * The version of the OpenAPI document: 1.7.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.LdContext;
import org.openapitools.client.model.LdContextMetadataInner;
import org.openapitools.client.model.RetrieveContext200ResponseOneOf;



import java.io.IOException;
import java.lang.reflect.Type;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.JsonPrimitive;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonSerializationContext;
import com.google.gson.JsonSerializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonArray;
import com.google.gson.JsonParseException;

import org.openapitools.client.JSON;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-25T10:47:39.074561198Z[Etc/UTC]", comments = "Generator version: 7.13.0-SNAPSHOT")
public class RetrieveContext200Response extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(RetrieveContext200Response.class.getName());

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!RetrieveContext200Response.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'RetrieveContext200Response' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<RetrieveContext200ResponseOneOf> adapterRetrieveContext200ResponseOneOf = gson.getDelegateAdapter(this, TypeToken.get(RetrieveContext200ResponseOneOf.class));

            final Type typeInstanceListLdContextMetadataInner = new TypeToken<List<LdContextMetadataInner>>(){}.getType();
            final TypeAdapter<List<LdContextMetadataInner>> adapterListLdContextMetadataInner = (TypeAdapter<List<LdContextMetadataInner>>) gson.getDelegateAdapter(this, TypeToken.get(typeInstanceListLdContextMetadataInner));

            return (TypeAdapter<T>) new TypeAdapter<RetrieveContext200Response>() {
                @Override
                public void write(JsonWriter out, RetrieveContext200Response value) throws IOException {
                    if (value == null || value.getActualInstance() == null) {
                        elementAdapter.write(out, null);
                        return;
                    }

                    // check if the actual instance is of the type `RetrieveContext200ResponseOneOf`
                    if (value.getActualInstance() instanceof RetrieveContext200ResponseOneOf) {
                        JsonElement element = adapterRetrieveContext200ResponseOneOf.toJsonTree((RetrieveContext200ResponseOneOf)value.getActualInstance());
                        elementAdapter.write(out, element);
                        return;
                    }
                    // check if the actual instance is of the type `List<LdContextMetadataInner>`
                    if (value.getActualInstance() instanceof List<?>) {
                        List<?> list = (List<?>) value.getActualInstance();
                        if (list.get(0) instanceof LdContextMetadataInner) {
                            JsonArray array = adapterListLdContextMetadataInner.toJsonTree((List<LdContextMetadataInner>)value.getActualInstance()).getAsJsonArray();
                            elementAdapter.write(out, array);
                            return;
                        }
                    }
                    throw new IOException("Failed to serialize as the type doesn't match oneOf schemas: List<LdContextMetadataInner>, RetrieveContext200ResponseOneOf");
                }

                @Override
                public RetrieveContext200Response read(JsonReader in) throws IOException {
                    Object deserialized = null;
                    JsonElement jsonElement = elementAdapter.read(in);

                    int match = 0;
                    ArrayList<String> errorMessages = new ArrayList<>();
                    TypeAdapter actualAdapter = elementAdapter;

                    // deserialize RetrieveContext200ResponseOneOf
                    try {
                        // validate the JSON object to see if any exception is thrown
                        RetrieveContext200ResponseOneOf.validateJsonElement(jsonElement);
                        actualAdapter = adapterRetrieveContext200ResponseOneOf;
                        match++;
                        log.log(Level.FINER, "Input data matches schema 'RetrieveContext200ResponseOneOf'");
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format("Deserialization for RetrieveContext200ResponseOneOf failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'RetrieveContext200ResponseOneOf'", e);
                    }
                    // deserialize List<LdContextMetadataInner>
                    try {
                        // validate the JSON object to see if any exception is thrown
                        if (!jsonElement.isJsonArray()) {
                            throw new IllegalArgumentException(String.format("Expected json element to be a array type in the JSON string but got `%s`", jsonElement.toString()));
                        }

                        JsonArray array = jsonElement.getAsJsonArray();
                        // validate array items
                        for(JsonElement element : array) {
                            LdContextMetadataInner.validateJsonElement(element);
                        }
                        actualAdapter = adapterListLdContextMetadataInner;
                        match++;
                        log.log(Level.FINER, "Input data matches schema 'List<LdContextMetadataInner>'");
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format("Deserialization for List<LdContextMetadataInner> failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'List<LdContextMetadataInner>'", e);
                    }

                    if (match == 1) {
                        RetrieveContext200Response ret = new RetrieveContext200Response();
                        ret.setActualInstance(actualAdapter.fromJsonTree(jsonElement));
                        return ret;
                    }

                    throw new IOException(String.format("Failed deserialization for RetrieveContext200Response: %d classes match result, expected 1. Detailed failure message for oneOf schemas: %s. JSON: %s", match, errorMessages, jsonElement.toString()));
                }
            }.nullSafe();
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, Class<?>> schemas = new HashMap<String, Class<?>>();

    public RetrieveContext200Response() {
        super("oneOf", Boolean.FALSE);
    }

    public RetrieveContext200Response(Object o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("RetrieveContext200ResponseOneOf", RetrieveContext200ResponseOneOf.class);
        schemas.put("List<LdContextMetadataInner>", List.class);
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return RetrieveContext200Response.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * List<LdContextMetadataInner>, RetrieveContext200ResponseOneOf
     *
     * It could be an instance of the 'oneOf' schemas.
     */
    @Override
    public void setActualInstance(Object instance) {
        if (instance instanceof RetrieveContext200ResponseOneOf) {
            super.setActualInstance(instance);
            return;
        }

        if (instance instanceof List<?>) {
            List<?> list = (List<?>) instance;
            if (list.get(0) instanceof LdContextMetadataInner) {
                super.setActualInstance(instance);
                return;
            }
        }

        throw new RuntimeException("Invalid instance type. Must be List<LdContextMetadataInner>, RetrieveContext200ResponseOneOf");
    }

    /**
     * Get the actual instance, which can be the following:
     * List<LdContextMetadataInner>, RetrieveContext200ResponseOneOf
     *
     * @return The actual instance (List<LdContextMetadataInner>, RetrieveContext200ResponseOneOf)
     */
    @SuppressWarnings("unchecked")
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `RetrieveContext200ResponseOneOf`. If the actual instance is not `RetrieveContext200ResponseOneOf`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `RetrieveContext200ResponseOneOf`
     * @throws ClassCastException if the instance is not `RetrieveContext200ResponseOneOf`
     */
    public RetrieveContext200ResponseOneOf getRetrieveContext200ResponseOneOf() throws ClassCastException {
        return (RetrieveContext200ResponseOneOf)super.getActualInstance();
    }

    /**
     * Get the actual instance of `List<LdContextMetadataInner>`. If the actual instance is not `List<LdContextMetadataInner>`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `List<LdContextMetadataInner>`
     * @throws ClassCastException if the instance is not `List<LdContextMetadataInner>`
     */
    public List<LdContextMetadataInner> getListLdContextMetadataInner() throws ClassCastException {
        return (List<LdContextMetadataInner>)super.getActualInstance();
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to RetrieveContext200Response
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        // validate oneOf schemas one by one
        int validCount = 0;
        ArrayList<String> errorMessages = new ArrayList<>();
        // validate the json string with RetrieveContext200ResponseOneOf
        try {
            RetrieveContext200ResponseOneOf.validateJsonElement(jsonElement);
            validCount++;
        } catch (Exception e) {
            errorMessages.add(String.format("Deserialization for RetrieveContext200ResponseOneOf failed with `%s`.", e.getMessage()));
            // continue to the next one
        }
        // validate the json string with List<LdContextMetadataInner>
        try {
            if (!jsonElement.isJsonArray()) {
                throw new IllegalArgumentException(String.format("Expected json element to be a array type in the JSON string but got `%s`", jsonElement.toString()));
            }
            JsonArray array = jsonElement.getAsJsonArray();
            // validate array items
            for(JsonElement element : array) {
                LdContextMetadataInner.validateJsonElement(element);
            }
            validCount++;
        } catch (Exception e) {
            errorMessages.add(String.format("Deserialization for List<LdContextMetadataInner> failed with `%s`.", e.getMessage()));
            // continue to the next one
        }
        if (validCount != 1) {
            throw new IOException(String.format("The JSON string is invalid for RetrieveContext200Response with oneOf schemas: List<LdContextMetadataInner>, RetrieveContext200ResponseOneOf. %d class(es) match the result, expected 1. Detailed failure message for oneOf schemas: %s. JSON: %s", validCount, errorMessages, jsonElement.toString()));
        }
    }

    /**
     * Create an instance of RetrieveContext200Response given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of RetrieveContext200Response
     * @throws IOException if the JSON string is invalid with respect to RetrieveContext200Response
     */
    public static RetrieveContext200Response fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, RetrieveContext200Response.class);
    }

    /**
     * Convert an instance of RetrieveContext200Response to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}

