/*
 * NGSI-LD OAS
 * OpenAPI Specification for NGSI-LD API.
 *
 * The version of the OpenAPI document: 1.7.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.net.URI;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.LdContext;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * RetrieveAttrTypes200Response1OneOf1Inner
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-25T10:47:39.074561198Z[Etc/UTC]", comments = "Generator version: 7.13.0-SNAPSHOT")
public class RetrieveAttrTypes200Response1OneOf1Inner {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nonnull
  private URI id;

  /**
   * JSON-LD @type. 
   */
  @JsonAdapter(TypeEnum.Adapter.class)
  public enum TypeEnum {
    ATTRIBUTE("Attribute");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<TypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return TypeEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      TypeEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  @javax.annotation.Nonnull
  private TypeEnum type;

  public static final String SERIALIZED_NAME_ATTRIBUTE_NAME = "attributeName";
  @SerializedName(SERIALIZED_NAME_ATTRIBUTE_NAME)
  @javax.annotation.Nonnull
  private String attributeName;

  public static final String SERIALIZED_NAME_ATTRIBUTE_COUNT = "attributeCount";
  @SerializedName(SERIALIZED_NAME_ATTRIBUTE_COUNT)
  @javax.annotation.Nullable
  private BigDecimal attributeCount;

  public static final String SERIALIZED_NAME_ATTRIBUTE_TYPES = "attributeTypes";
  @SerializedName(SERIALIZED_NAME_ATTRIBUTE_TYPES)
  @javax.annotation.Nullable
  private List<String> attributeTypes = new ArrayList<>();

  public static final String SERIALIZED_NAME_TYPE_NAMES = "typeNames";
  @SerializedName(SERIALIZED_NAME_TYPE_NAMES)
  @javax.annotation.Nullable
  private List<String> typeNames = new ArrayList<>();

  public static final String SERIALIZED_NAME_AT_CONTEXT = "@context";
  @SerializedName(SERIALIZED_NAME_AT_CONTEXT)
  @javax.annotation.Nonnull
  private LdContext atContext;

  public RetrieveAttrTypes200Response1OneOf1Inner() {
  }

  public RetrieveAttrTypes200Response1OneOf1Inner id(@javax.annotation.Nonnull URI id) {
    this.id = id;
    return this;
  }

  /**
   * Full URI of attribute name. 
   * @return id
   */
  @javax.annotation.Nonnull
  public URI getId() {
    return id;
  }

  public void setId(@javax.annotation.Nonnull URI id) {
    this.id = id;
  }


  public RetrieveAttrTypes200Response1OneOf1Inner type(@javax.annotation.Nonnull TypeEnum type) {
    this.type = type;
    return this;
  }

  /**
   * JSON-LD @type. 
   * @return type
   */
  @javax.annotation.Nonnull
  public TypeEnum getType() {
    return type;
  }

  public void setType(@javax.annotation.Nonnull TypeEnum type) {
    this.type = type;
  }


  public RetrieveAttrTypes200Response1OneOf1Inner attributeName(@javax.annotation.Nonnull String attributeName) {
    this.attributeName = attributeName;
    return this;
  }

  /**
   * Name of the attribute, short name if contained in @context. 
   * @return attributeName
   */
  @javax.annotation.Nonnull
  public String getAttributeName() {
    return attributeName;
  }

  public void setAttributeName(@javax.annotation.Nonnull String attributeName) {
    this.attributeName = attributeName;
  }


  public RetrieveAttrTypes200Response1OneOf1Inner attributeCount(@javax.annotation.Nullable BigDecimal attributeCount) {
    this.attributeCount = attributeCount;
    return this;
  }

  /**
   * Number of attribute instances with this attribute name. 
   * @return attributeCount
   */
  @javax.annotation.Nullable
  public BigDecimal getAttributeCount() {
    return attributeCount;
  }

  public void setAttributeCount(@javax.annotation.Nullable BigDecimal attributeCount) {
    this.attributeCount = attributeCount;
  }


  public RetrieveAttrTypes200Response1OneOf1Inner attributeTypes(@javax.annotation.Nullable List<String> attributeTypes) {
    this.attributeTypes = attributeTypes;
    return this;
  }

  public RetrieveAttrTypes200Response1OneOf1Inner addAttributeTypesItem(String attributeTypesItem) {
    if (this.attributeTypes == null) {
      this.attributeTypes = new ArrayList<>();
    }
    this.attributeTypes.add(attributeTypesItem);
    return this;
  }

  /**
   * List of attribute types (e.g. Property, Relationship, GeoProperty) for which entity instances exist, which contain an attribute with this name. 
   * @return attributeTypes
   */
  @javax.annotation.Nullable
  public List<String> getAttributeTypes() {
    return attributeTypes;
  }

  public void setAttributeTypes(@javax.annotation.Nullable List<String> attributeTypes) {
    this.attributeTypes = attributeTypes;
  }


  public RetrieveAttrTypes200Response1OneOf1Inner typeNames(@javax.annotation.Nullable List<String> typeNames) {
    this.typeNames = typeNames;
    return this;
  }

  public RetrieveAttrTypes200Response1OneOf1Inner addTypeNamesItem(String typeNamesItem) {
    if (this.typeNames == null) {
      this.typeNames = new ArrayList<>();
    }
    this.typeNames.add(typeNamesItem);
    return this;
  }

  /**
   * List of entity type names for which entity instances exist containing attributes that have the respective name. 
   * @return typeNames
   */
  @javax.annotation.Nullable
  public List<String> getTypeNames() {
    return typeNames;
  }

  public void setTypeNames(@javax.annotation.Nullable List<String> typeNames) {
    this.typeNames = typeNames;
  }


  public RetrieveAttrTypes200Response1OneOf1Inner atContext(@javax.annotation.Nonnull LdContext atContext) {
    this.atContext = atContext;
    return this;
  }

  /**
   * Get atContext
   * @return atContext
   */
  @javax.annotation.Nonnull
  public LdContext getAtContext() {
    return atContext;
  }

  public void setAtContext(@javax.annotation.Nonnull LdContext atContext) {
    this.atContext = atContext;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the RetrieveAttrTypes200Response1OneOf1Inner instance itself
   */
  public RetrieveAttrTypes200Response1OneOf1Inner putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RetrieveAttrTypes200Response1OneOf1Inner retrieveAttrTypes200Response1OneOf1Inner = (RetrieveAttrTypes200Response1OneOf1Inner) o;
    return Objects.equals(this.id, retrieveAttrTypes200Response1OneOf1Inner.id) &&
        Objects.equals(this.type, retrieveAttrTypes200Response1OneOf1Inner.type) &&
        Objects.equals(this.attributeName, retrieveAttrTypes200Response1OneOf1Inner.attributeName) &&
        Objects.equals(this.attributeCount, retrieveAttrTypes200Response1OneOf1Inner.attributeCount) &&
        Objects.equals(this.attributeTypes, retrieveAttrTypes200Response1OneOf1Inner.attributeTypes) &&
        Objects.equals(this.typeNames, retrieveAttrTypes200Response1OneOf1Inner.typeNames) &&
        Objects.equals(this.atContext, retrieveAttrTypes200Response1OneOf1Inner.atContext)&&
        Objects.equals(this.additionalProperties, retrieveAttrTypes200Response1OneOf1Inner.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, type, attributeName, attributeCount, attributeTypes, typeNames, atContext, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RetrieveAttrTypes200Response1OneOf1Inner {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    attributeName: ").append(toIndentedString(attributeName)).append("\n");
    sb.append("    attributeCount: ").append(toIndentedString(attributeCount)).append("\n");
    sb.append("    attributeTypes: ").append(toIndentedString(attributeTypes)).append("\n");
    sb.append("    typeNames: ").append(toIndentedString(typeNames)).append("\n");
    sb.append("    atContext: ").append(toIndentedString(atContext)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("type");
    openapiFields.add("attributeName");
    openapiFields.add("attributeCount");
    openapiFields.add("attributeTypes");
    openapiFields.add("typeNames");
    openapiFields.add("@context");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("id");
    openapiRequiredFields.add("type");
    openapiRequiredFields.add("attributeName");
    openapiRequiredFields.add("@context");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to RetrieveAttrTypes200Response1OneOf1Inner
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!RetrieveAttrTypes200Response1OneOf1Inner.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in RetrieveAttrTypes200Response1OneOf1Inner is not found in the empty JSON string", RetrieveAttrTypes200Response1OneOf1Inner.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : RetrieveAttrTypes200Response1OneOf1Inner.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if (!jsonObj.get("type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("type").toString()));
      }
      // validate the required field `type`
      TypeEnum.validateJsonElement(jsonObj.get("type"));
      if (!jsonObj.get("attributeName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `attributeName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("attributeName").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("attributeTypes") != null && !jsonObj.get("attributeTypes").isJsonNull() && !jsonObj.get("attributeTypes").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `attributeTypes` to be an array in the JSON string but got `%s`", jsonObj.get("attributeTypes").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("typeNames") != null && !jsonObj.get("typeNames").isJsonNull() && !jsonObj.get("typeNames").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `typeNames` to be an array in the JSON string but got `%s`", jsonObj.get("typeNames").toString()));
      }
      // validate the required field `@context`
      LdContext.validateJsonElement(jsonObj.get("@context"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!RetrieveAttrTypes200Response1OneOf1Inner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'RetrieveAttrTypes200Response1OneOf1Inner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<RetrieveAttrTypes200Response1OneOf1Inner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(RetrieveAttrTypes200Response1OneOf1Inner.class));

       return (TypeAdapter<T>) new TypeAdapter<RetrieveAttrTypes200Response1OneOf1Inner>() {
           @Override
           public void write(JsonWriter out, RetrieveAttrTypes200Response1OneOf1Inner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public RetrieveAttrTypes200Response1OneOf1Inner read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             RetrieveAttrTypes200Response1OneOf1Inner instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of RetrieveAttrTypes200Response1OneOf1Inner given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of RetrieveAttrTypes200Response1OneOf1Inner
   * @throws IOException if the JSON string is invalid with respect to RetrieveAttrTypes200Response1OneOf1Inner
   */
  public static RetrieveAttrTypes200Response1OneOf1Inner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, RetrieveAttrTypes200Response1OneOf1Inner.class);
  }

  /**
   * Convert an instance of RetrieveAttrTypes200Response1OneOf1Inner to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

