/*
 * NGSI-LD OAS
 * OpenAPI Specification for NGSI-LD API.
 *
 * The version of the OpenAPI document: 1.7.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.Attribute;
import org.openapitools.client.model.EntityTypeInfo;
import org.openapitools.client.model.Feature;
import org.openapitools.client.model.FeatureCollection;
import org.openapitools.client.model.OptionsRepresentation;
import org.openapitools.client.model.ProblemDetails;
import org.openapitools.client.model.Query;
import org.openapitools.client.model.QueryBatchRequest;
import org.openapitools.client.model.QueryEntity200ResponseInner;
import org.openapitools.client.model.QueryEntity200ResponseInner1;
import org.openapitools.client.model.QueryEntityCoordinatesParameter;
import org.openapitools.client.model.QueryEntityGeorelParameter;
import org.openapitools.client.model.QueryEntityOptionsParameterInner;
import org.openapitools.client.model.RetrieveAttrTypes200Response;
import org.openapitools.client.model.RetrieveAttrTypes200Response1;
import org.openapitools.client.model.RetrieveAttrTypes200Response1OneOf1Inner;
import org.openapitools.client.model.RetrieveEntityTypeInfo200Response;
import org.openapitools.client.model.RetrieveEntityTypes200Response;
import org.openapitools.client.model.RetrieveEntityTypes200Response1;
import java.net.URI;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ContextInformationConsumptionApi
 */
@Disabled
public class ContextInformationConsumptionApiTest {

    private final ContextInformationConsumptionApi api = new ContextInformationConsumptionApi();

    /**
     * Query entities based on POST 
     *
     * 5.7.2 Query Entity (batch entity queries only).  This operation allows querying an NGSI-LD system. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void queryBatchTest() throws ApiException {
        Boolean count = null;
        Integer limit = null;
        Boolean local = null;
        List<OptionsRepresentation> options = null;
        URI link = null;
        String ngSILDTenant = null;
        Query query = null;
        List<QueryEntity200ResponseInner> response = api.queryBatch(count, limit, local, options, link, ngSILDTenant, query);
        // TODO: test validations
    }

    /**
     * Query entities 
     *
     * 5.7.2 Query Entities (excluding batch entity queries).  This operation allows querying an NGSI-LD system. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void queryEntityTest() throws ApiException {
        List<URI> id = null;
        String type = null;
        String idPattern = null;
        List<String> attrs = null;
        String q = null;
        String csf = null;
        String geometry = null;
        QueryEntityGeorelParameter georel = null;
        QueryEntityCoordinatesParameter coordinates = null;
        String geoproperty = null;
        String geometryProperty = null;
        String lang = null;
        String scopeQ = null;
        Integer limit = null;
        Boolean count = null;
        List<QueryEntityOptionsParameterInner> options = null;
        Boolean local = null;
        URI link = null;
        String ngSILDTenant = null;
        List<QueryEntity200ResponseInner> response = api.queryEntity(id, type, idPattern, attrs, q, csf, geometry, georel, coordinates, geoproperty, geometryProperty, lang, scopeQ, limit, count, options, local, link, ngSILDTenant);
        // TODO: test validations
    }

    /**
     * Details about available attribute 
     *
     * 5.7.10 Retrieve Available Attribute Information.  This operation allows retrieving detailed attribute information about a specified NGSI-LD attribute that belongs to entity instances existing within the NGSI-LD system. The detailed representation includes the attribute name (as short name if available in the provided @context) and the type names for which entity instances exist that have the respective attribute, a count of available attribute instances and a list of types the attribute can have (e.g. Property, Relationship or GeoProperty). 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void retrieveAttrTypeInfoTest() throws ApiException {
        URI attrId = null;
        Boolean local = null;
        URI link = null;
        String ngSILDTenant = null;
        Attribute response = api.retrieveAttrTypeInfo(attrId, local, link, ngSILDTenant);
        // TODO: test validations
    }

    /**
     * Available attributes 
     *
     * 5.7.8 Retrieve Available Attributes.  This operation allows retrieving a list of NGSI-LD attributes that belong to entity instances existing within the NGSI- LD system.  5.7.9 Retrieve Details of Available Attributes.  This operation allows retrieving a list with a detailed representation of NGSI-LD  attributes that belong to entity instances existing within the NGSI-LD system. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void retrieveAttrTypesTest() throws ApiException {
        Boolean details = null;
        Boolean local = null;
        URI link = null;
        String ngSILDTenant = null;
        RetrieveAttrTypes200Response response = api.retrieveAttrTypes(details, local, link, ngSILDTenant);
        // TODO: test validations
    }

    /**
     * Entity retrieval by id 
     *
     * 5.7.1 Retrieve Entity.  This operation allows retrieving an NGSI-LD Entity. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void retrieveEntityTest() throws ApiException {
        URI entityId = null;
        String type = null;
        List<String> attrs = null;
        String geometryProperty = null;
        String lang = null;
        List<QueryEntityOptionsParameterInner> options = null;
        Boolean local = null;
        URI link = null;
        String ngSILDTenant = null;
        QueryEntity200ResponseInner response = api.retrieveEntity(entityId, type, attrs, geometryProperty, lang, options, local, link, ngSILDTenant);
        // TODO: test validations
    }

    /**
     * Details about available entity type 
     *
     * 5.7.7 Retrieve Available Entity Type information.  This operation allows retrieving detailed entity type information about a specified NGSI-LD entity type for which entity instances exist within the NGSI-LD system. The detailed representation includes the type name (as short name if available in the provided @context), the count of available entity instances and details about attributes that existing instances of this entity type have, including their name (as short name if available in the provided @context) and a list of types the attribute can have (e.g. Property, Relationship or GeoProperty). 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void retrieveEntityTypeInfoTest() throws ApiException {
        URI type = null;
        Boolean local = null;
        URI link = null;
        String ngSILDTenant = null;
        EntityTypeInfo response = api.retrieveEntityTypeInfo(type, local, link, ngSILDTenant);
        // TODO: test validations
    }

    /**
     * Retrieve available entity types  
     *
     * 5.7.5 Retrieve Available Entity Types.  This operation allows retrieving a list of NGSI-LD entity types for which entity instances exist within the NGSI-LD system.  5.7.6  Retrieve Details of Available Entity Types.  This operation allows retrieving a list with a detailed representation of NGSI-LD entity types for which entity instances exist within the NGSI-LD system. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void retrieveEntityTypesTest() throws ApiException {
        Boolean details = null;
        Boolean local = null;
        URI link = null;
        String ngSILDTenant = null;
        RetrieveEntityTypes200Response response = api.retrieveEntityTypes(details, local, link, ngSILDTenant);
        // TODO: test validations
    }

}
