/*
 * NGSI-LD OAS
 * OpenAPI Specification for NGSI-LD API.
 *
 * The version of the OpenAPI document: 1.7.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.math.BigDecimal;
import java.util.List;
import org.openapitools.client.model.GeometryLineString;
import org.openapitools.client.model.GeometryLinearRing;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for QueryEntityCoordinatesParameter
 */
public class QueryEntityCoordinatesParameterTest {
    private final QueryEntityCoordinatesParameter model = new QueryEntityCoordinatesParameter();

    /**
     * Model tests for QueryEntityCoordinatesParameter
     */
    @Test
    public void testQueryEntityCoordinatesParameter() {
        // TODO: test QueryEntityCoordinatesParameter
    }

}
