/*
 * NGSI-LD OAS
 * OpenAPI Specification for NGSI-LD API.
 *
 * The version of the OpenAPI document: 1.7.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.openapitools.client.model.ProvidedBy;
import org.openapitools.client.model.Reliability;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AvailableSpotNumber
 */
public class AvailableSpotNumberTest {
    private final AvailableSpotNumber model = new AvailableSpotNumber();

    /**
     * Model tests for AvailableSpotNumber
     */
    @Test
    public void testAvailableSpotNumber() {
        // TODO: test AvailableSpotNumber
    }

    /**
     * Test the property 'value'
     */
    @Test
    public void valueTest() {
        // TODO: test value
    }

    /**
     * Test the property 'reliability'
     */
    @Test
    public void reliabilityTest() {
        // TODO: test reliability
    }

    /**
     * Test the property 'providedBy'
     */
    @Test
    public void providedByTest() {
        // TODO: test providedBy
    }

}
