/*
 * NGSI-LD OAS
 * OpenAPI Specification for NGSI-LD API.
 *
 * The version of the OpenAPI document: 1.7.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.Endpoint;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for NotificationParams
 */
public class NotificationParamsTest {
    private final NotificationParams model = new NotificationParams();

    /**
     * Model tests for NotificationParams
     */
    @Test
    public void testNotificationParams() {
        // TODO: test NotificationParams
    }

    /**
     * Test the property 'attributes'
     */
    @Test
    public void attributesTest() {
        // TODO: test attributes
    }

    /**
     * Test the property 'sysAttrs'
     */
    @Test
    public void sysAttrsTest() {
        // TODO: test sysAttrs
    }

    /**
     * Test the property 'format'
     */
    @Test
    public void formatTest() {
        // TODO: test format
    }

    /**
     * Test the property 'showChanges'
     */
    @Test
    public void showChangesTest() {
        // TODO: test showChanges
    }

    /**
     * Test the property 'endpoint'
     */
    @Test
    public void endpointTest() {
        // TODO: test endpoint
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'timesSent'
     */
    @Test
    public void timesSentTest() {
        // TODO: test timesSent
    }

    /**
     * Test the property 'timesFailed'
     */
    @Test
    public void timesFailedTest() {
        // TODO: test timesFailed
    }

    /**
     * Test the property 'lastNotification'
     */
    @Test
    public void lastNotificationTest() {
        // TODO: test lastNotification
    }

    /**
     * Test the property 'lastFailure'
     */
    @Test
    public void lastFailureTest() {
        // TODO: test lastFailure
    }

    /**
     * Test the property 'lastSuccess'
     */
    @Test
    public void lastSuccessTest() {
        // TODO: test lastSuccess
    }

}
