/*
 * NGSI-LD OAS
 * OpenAPI Specification for NGSI-LD API.
 *
 * The version of the OpenAPI document: 1.7.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import org.openapitools.client.model.OptionsRepresentation;
import org.openapitools.client.model.OptionsSysAttrs;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for QueryEntityOptionsParameterInner
 */
public class QueryEntityOptionsParameterInnerTest {
    private final QueryEntityOptionsParameterInner model = new QueryEntityOptionsParameterInner();

    /**
     * Model tests for QueryEntityOptionsParameterInner
     */
    @Test
    public void testQueryEntityOptionsParameterInner() {
        // TODO: test QueryEntityOptionsParameterInner
    }

}
