/*
 * NGSI-LD OAS
 * OpenAPI Specification for NGSI-LD API.
 *
 * The version of the OpenAPI document: 1.7.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.EntityInfo;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RegistrationInfo
 */
public class RegistrationInfoTest {
    private final RegistrationInfo model = new RegistrationInfo();

    /**
     * Model tests for RegistrationInfo
     */
    @Test
    public void testRegistrationInfo() {
        // TODO: test RegistrationInfo
    }

    /**
     * Test the property 'entities'
     */
    @Test
    public void entitiesTest() {
        // TODO: test entities
    }

    /**
     * Test the property 'propertyNames'
     */
    @Test
    public void propertyNamesTest() {
        // TODO: test propertyNames
    }

    /**
     * Test the property 'relationshipNames'
     */
    @Test
    public void relationshipNamesTest() {
        // TODO: test relationshipNames
    }

}
