/*
 * NGSI-LD OAS
 * OpenAPI Specification for NGSI-LD API.
 *
 * The version of the OpenAPI document: 1.7.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.net.URI;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.LdContext;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RetrieveAttrTypes200Response1OneOf
 */
public class RetrieveAttrTypes200Response1OneOfTest {
    private final RetrieveAttrTypes200Response1OneOf model = new RetrieveAttrTypes200Response1OneOf();

    /**
     * Model tests for RetrieveAttrTypes200Response1OneOf
     */
    @Test
    public void testRetrieveAttrTypes200Response1OneOf() {
        // TODO: test RetrieveAttrTypes200Response1OneOf
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'attributeList'
     */
    @Test
    public void attributeListTest() {
        // TODO: test attributeList
    }

    /**
     * Test the property 'atContext'
     */
    @Test
    public void atContextTest() {
        // TODO: test atContext
    }

}
