version: "3.5"
services:
  context-catalog:
    image: halverneus/static-file-server
    hostname: context-catalog
    container_name: context-catalog
    expose:
      - "8080"
    ports:
      - "8080:8080"
    volumes:
      - ./docker/context-catalog:/web
  postgres:
    image: postgis/postgis
    ports:
      - "5432"
    environment:
      POSTGRES_USER: ngb
      POSTGRES_PASSWORD: ngb
      POSTGRES_DB: ngb
  scorpio:
    image: scorpiobroker/all-in-one-runner:java-latest
    hostname: scorpio
    container_name: scorpio
    ports:
      - "9090:9090"
    depends_on:
      - postgres
  scorpio-notifier-tester:
    build:
      context: .
      dockerfile: ./docker/scorpio-notifier-tester/Dockerfile
    hostname: scorpio-notifier
    container_name: scorpio-notifier
    expose:
      - "8084"
    ports:
      - "8084:8084"
    volumes:
      - ./docker/scorpio-notifier-tester/scorpio_notifier_tester:/opt/scorpio-notifier-tester/scorpio_notifier_tester
    depends_on:
      - scorpio
      - postgres

