version: "3.5"
services:
  context-catalog:
    image: halverneus/static-file-server
    hostname: context-catalog
    container_name: context-catalog
    expose:
      - "8080"
    ports:
      - "8080:8080"
    volumes:
      - ./docker/context-catalog:/web
  orion:
    image: fiware/orion-ld
    hostname: orion
    container_name: fiware-orion
    expose:
      - "1026"
    ports:
      - "1026:1026"
    depends_on:
      - mongo-db
    command: -dbhost mongo-db -logLevel DEBUG
  mongo-db:
    image: mongo:3.6
    hostname: mongo-db
    container_name: mongo-db
    ports:
      - "27017:27017" 
    networks:
      - default
    command: --nojournal
    volumes:
      - mongo-db:/data
  scorpio-notifier-tester:
    build:
      context: .
      dockerfile: ./docker/scorpio-notifier-tester/Dockerfile
    hostname: scorpio-notifier
    container_name: scorpio-notifier
    expose:
      - "8084"
    ports:
      - "8084:8084"
    volumes:
      - ./docker/scorpio-notifier-tester/scorpio_notifier_tester:/opt/scorpio-notifier-tester/scorpio_notifier_tester
    depends_on:
      - orion
volumes:
  mongo-db: ~
