/*
 * NGSI-LD OAS
 * OpenAPI Specification for NGSI-LD API.
 *
 * The version of the OpenAPI document: 1.7.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.annotations.SerializedName;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for OptionsSysAttrs
 */
public class OptionsSysAttrsTest {
    /**
     * Model tests for OptionsSysAttrs
     */
    @Test
    public void testOptionsSysAttrs() {
        // TODO: test OptionsSysAttrs
    }

}
