/*
 * NGSI-LD OAS
 * OpenAPI Specification for NGSI-LD API.
 *
 * The version of the OpenAPI document: 1.7.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.EntitySelector;
import org.openapitools.client.model.GeoQuery;
import org.openapitools.client.model.TemporalQuery;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for QueryTemporal
 */
public class QueryTemporalTest {
    private final QueryTemporal model = new QueryTemporal();

    /**
     * Model tests for QueryTemporal
     */
    @Test
    public void testQueryTemporal() {
        // TODO: test QueryTemporal
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'entities'
     */
    @Test
    public void entitiesTest() {
        // TODO: test entities
    }

    /**
     * Test the property 'attrs'
     */
    @Test
    public void attrsTest() {
        // TODO: test attrs
    }

    /**
     * Test the property 'q'
     */
    @Test
    public void qTest() {
        // TODO: test q
    }

    /**
     * Test the property 'geoQ'
     */
    @Test
    public void geoQTest() {
        // TODO: test geoQ
    }

    /**
     * Test the property 'csf'
     */
    @Test
    public void csfTest() {
        // TODO: test csf
    }

    /**
     * Test the property 'scopeQ'
     */
    @Test
    public void scopeQTest() {
        // TODO: test scopeQ
    }

    /**
     * Test the property 'lang'
     */
    @Test
    public void langTest() {
        // TODO: test lang
    }

    /**
     * Test the property 'temporalQ'
     */
    @Test
    public void temporalQTest() {
        // TODO: test temporalQ
    }

}
