/*
 * NGSI-LD OAS
 * OpenAPI Specification for NGSI-LD API.
 *
 * The version of the OpenAPI document: 1.7.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TemporalQuery
 */
public class TemporalQueryTest {
    private final TemporalQuery model = new TemporalQuery();

    /**
     * Model tests for TemporalQuery
     */
    @Test
    public void testTemporalQuery() {
        // TODO: test TemporalQuery
    }

    /**
     * Test the property 'timerel'
     */
    @Test
    public void timerelTest() {
        // TODO: test timerel
    }

    /**
     * Test the property 'timeAt'
     */
    @Test
    public void timeAtTest() {
        // TODO: test timeAt
    }

    /**
     * Test the property 'endTimeAt'
     */
    @Test
    public void endTimeAtTest() {
        // TODO: test endTimeAt
    }

    /**
     * Test the property 'timeproperty'
     */
    @Test
    public void timepropertyTest() {
        // TODO: test timeproperty
    }

}
